language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- ant run-tests
script:
- ant
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: Qt3mVGTHq2AxlvLlvCJC4NLNr6VNTrsv7qyjtrIePZ84P3fsHsoRd3IPWDyYrWIkXw3IIsMCABk0/l/cAT8Yr+xS/B+hP2Im5VW+FfKl6hFkCYTKnTdbPDAff+/vGeABWFYZ5xa8AnDLfIiSpy7q/v/iprpm+J+ezUaja1WbklCWjyXmnqegi6dkoKZnKfcckIMCfZdHbGKfam6SMngG0iyPePCrgui4681cIcliGy77kpYHjmrBZf2Ad5kL/Rdu1j4HOwoJI0xZDM1EW/SZWkAKA8pI9D+9kPcvUVMsw9jh1J2ZEjo3nhAV5NaxUMZf61u0tbYSmOANQygHKqkIVEvKewjGrxMImwLpq16Y5OvD2D2uG+5DdjiWWmR1BzOrTs1pUMF+x7MWGR5j5Zr59Qfc6ogrzeXSBQP4BPYyzd5juguHgYbPRyPTvq1sChFZ7NVpAn1vTJ4P0mtxd+Z+ZmXruV3qd2b1rqeFQ7sNlSbVwLU8lldMCSp0Px/cVySnrScLQTg/ZhCUiziWfxJtuYRAMTqfjtcsiy8/TD50lWf30PCJZ1rRjkPHkLIiSt0l7Smp8t0iuzJz/6gp7F86gwc3xod/NHX4iOe00i0wrj3dEQW8KRdpIBgeoh8ih2Jgyjig0E+UEsj1qOEEklK1SSXE+ULGgMPPtEdvfkiv3GI=
  email: false
